module.exports = {
  purge: ["./src/**/*.js"],
  theme: {
    extend: {
      fontFamily: {
        heading: ['"Roboto Condensed"', "sans-serif"],
        serif: [
          "Roboto",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      maxWidth: {
        "7xl": "90rem",
      },
      minHeight: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "screen-sm": "640px",
        "screen-md": "768px",
        "screen-lg": "1024px",
        "screen-xl": "1280px",
        none: "none",
      },
      padding: {
        "72": "18rem",
        "80": "20rem",
      },
      inset: {
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
      },
      backgroundOpacity: {
        "5": "0.05",
        "10": "0.1",
        "15": "0.15",
        "20": "0.2",
        "25": "0.25",
        "30": "0.3",
        "35": "0.35",
        "40": "0.4",
        "45": "0.45",
        "50": "0.5",
        "55": "0.55",
        "60": "0.6",
        "65": "0.65",
        "70": "0.7",
        "75": "0.75",
        "80": "0.8",
        "85": "0.85",
        "90": "0.9",
        "95": "0.95",
      },
    },
  },
  variants: {},
  plugins: [],
}
